apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: two-tier-app
  name: two-tier-app-service
  namespace: app
spec:
  ports:
    - nodePort: 30006
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: two-tier-app
  type: NodePort
